GET http://localhost:5000/home
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwODkzODM5MywianRpIjoiZjNmM2M5ZWYtYWU1My00ZWI2LTkxM2EtNjFlZGQyMzc2YTA5IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MSwibmJmIjoxNzA4OTM4MzkzLCJjc3JmIjoiMmVkMGI0OGUtYWVhNS00YzUzLWJjMzgtZGY2ZTllNDM5NGIyIiwiZXhwIjoxNzA4OTQ1NTkzLCJhZG1pbiI6IjE0NjAzIn0.PyUOCeiGQOpkaVe-hq47b6ecsizi3WKXfgKoymLth_A


POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "alex@gmail.com",
  "password": "alex"
}

GET http://localhost:5000/logout
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwODkzOTI0NSwianRpIjoiMTdlODIyNzUtOGUwZC00MGZlLWIyYzItN2NhOWYxMmU1ZDNlIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MSwibmJmIjoxNzA4OTM5MjQ1LCJjc3JmIjoiZTM0ODZiNzItMjExNS00YjBiLWIzMDEtZTE4YTI1Y2ZiNWYxIiwiZXhwIjoxNzA4OTQ2NDQ1LCJhZG1pbiI6IjE0NjAzIn0.FshwttMN3GATRwxXLgQVz6raBbm_rGkafrtH4d6peTY




GET http://localhost:5000/posts
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwODk0MTM0NCwianRpIjoiZTM3NTM3ZmMtZGE1MS00YmZmLWE0NTAtNjM4YzVlZDU4ODViIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MiwibmJmIjoxNzA4OTQxMzQ0LCJjc3JmIjoiMWM3NzQ3MmEtZmU4Zi00ZWQ0LTkwYjctMzQ2OTdjNDVjZGMyIiwiZXhwIjoxNzA4OTQ4NTQ0LCJhZG1pbiI6bnVsbH0.hlt3JsLWTLBY7yGe8NlxjLrCfcKcpcAj8ZXN5bcN8SU



POST http://localhost:5000/posts
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwODk0MTM0NCwianRpIjoiZTM3NTM3ZmMtZGE1MS00YmZmLWE0NTAtNjM4YzVlZDU4ODViIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MiwibmJmIjoxNzA4OTQxMzQ0LCJjc3JmIjoiMWM3NzQ3MmEtZmU4Zi00ZWQ0LTkwYjctMzQ2OTdjNDVjZGMyIiwiZXhwIjoxNzA4OTQ4NTQ0LCJhZG1pbiI6bnVsbH0.hlt3JsLWTLBY7yGe8NlxjLrCfcKcpcAj8ZXN5bcN8SU

{
  "post_url": "fab@gmail.com",
  "post_description": "farbean"
}




PATCH http://localhost:5000/posts/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwODk0MDIxNCwianRpIjoiZDc0MDhmOTQtZTNjYy00NTU5LWE0NjgtYzU5NjljYzJmNzdjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MSwibmJmIjoxNzA4OTQwMjE0LCJjc3JmIjoiN2M3NjcwODktYTUyNS00Nzc5LWFiYzktODdiZGY4NGFhMzE2IiwiZXhwIjoxNzA4OTQ3NDE0LCJhZG1pbiI6IjE0NjAzIn0.VbSgW_ndpjbynMFBG9iO73hKMzWNivUsG99yaCAbVEI

{
  "post_url": "maki@gmail.com",
  "post_description": "farbean"
}


DELETE http://localhost:5000/posts/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwODk0MTM0NCwianRpIjoiZTM3NTM3ZmMtZGE1MS00YmZmLWE0NTAtNjM4YzVlZDU4ODViIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MiwibmJmIjoxNzA4OTQxMzQ0LCJjc3JmIjoiMWM3NzQ3MmEtZmU4Zi00ZWQ0LTkwYjctMzQ2OTdjNDVjZGMyIiwiZXhwIjoxNzA4OTQ4NTQ0LCJhZG1pbiI6bnVsbH0.hlt3JsLWTLBY7yGe8NlxjLrCfcKcpcAj8ZXN5bcN8SU
